pub mod res;
pub use res::{
  http_ok_static,
  http_ok_stream,
  http_no_content,
  http_created,
  http_accepted,
  http_partial_content,
  http_bad_static,
  http_unauthorized,
  http_forbidden,
  http_not_found,
  http_method_not_allowed,
  http_unsupported_media,
  http_too_many_requests,
  http_service_unavailable,
  http_server_error,
  send_file_fast,
  stream_file_chunked,
  send_file_range,
  http_brotli,
  http_lz4,
  parse_multipart_stream,
  parse_json_fast,
  parse_range,
  upload_with_progress,
  upload_streaming
};