name: Publish to crates.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo Check
        run: cargo check --workspace --all-targets

      - name: Log in to crates.io
        run: cargo login ${{ secrets.IO_TOKEN }}

      - name: Publish Crates
        run: |
          cargo publish -p crate_name_1
          cargo publish -p crate_name_2
