name: Publish to crates.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: A Safety Check
        run: cargo check --workspace --all-targets

      - name: Publish to crates.io
        run: cargo publish ${{ secrets.IO_TOKEN }}